global:
# Default is every 1 minute.
  scrape_interval: 15s 

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
# Here it's Prometheus itself.
# Job to scrape Prometheus metrics
  - job_name: 'prometheus' 
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
# Here it's spring application.
  - job_name: 'springboot-actuator'
# Job to scrape application metrics
    metrics_path: '/actuator/prometheus' 
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9092']
